"""ispublic field

Revision ID: d981e821bfa3
Revises: 002
Create Date: 2026-05-15 13:43:50.101698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd981e821bfa3'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edges', 'from_port',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'right'::character varying"))
    op.alter_column('edges', 'to_port',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'left'::character varying"))
    op.alter_column('edges', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('edges', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('nodes', 'shape',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'rectangle'::character varying"))
    op.alter_column('nodes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('nodes', 'body',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('nodes', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('nodes', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('nodes', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('projects', 'collaborators',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('projects', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('projects', 'camera',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text('\'{"x": 0, "y": 0, "zoom": 1}\'::jsonb'))
    op.alter_column('snapshots', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snapshots', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('projects', 'camera',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text('\'{"x": 0, "y": 0, "zoom": 1}\'::jsonb'))
    op.alter_column('projects', 'settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('projects', 'collaborators',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('nodes', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('nodes', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('nodes', 'tags',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('nodes', 'body',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('nodes', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('nodes', 'shape',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'rectangle'::character varying"))
    op.alter_column('edges', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('edges', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('edges', 'to_port',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'left'::character varying"))
    op.alter_column('edges', 'from_port',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'right'::character varying"))
    # ### end Alembic commands ###
